# Generated by Django 6.0.6 on 2026-06-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('fifa_code', models.CharField(help_text='e.g. FRA, SCO', max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('fifa_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, help_text='Group letter, e.g. C', max_length=1)),
                ('confederation', models.CharField(blank=True, choices=[('AFC', 'AFC (Asia)'), ('CAF', 'CAF (Africa)'), ('CONCACAF', 'CONCACAF (North/Central America)'), ('CONMEBOL', 'CONMEBOL (South America)'), ('OFC', 'OFC (Oceania)'), ('UEFA', 'UEFA (Europe)')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('venue_type', models.CharField(choices=[('bar', 'Bar / pub'), ('brewery', 'Brewery / taproom'), ('restaurant', 'Restaurant'), ('plaza', 'Public plaza / fan festival'), ('park', 'Park / outdoor space'), ('community', 'Municipal / community space'), ('hotel', 'Hotel'), ('entertainment', 'Entertainment (bowling, arcade)'), ('market', 'Food hall / market'), ('waterfront', 'Waterfront / boat'), ('university', 'University'), ('stadium', 'Stadium')], max_length=16)),
                ('environment', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('mixed', 'Indoor & outdoor')], default='indoor', max_length=8)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('greater_boston', 'Greater Boston'), ('cambridge_somerville', 'Cambridge / Somerville'), ('north_shore', 'North Shore'), ('south_shore', 'South Shore'), ('metrowest', 'MetroWest'), ('foxborough', 'Foxborough / Gillette'), ('worcester', 'Worcester / Central'), ('other', 'Other')], default='greater_boston', max_length=24)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('serves_alcohol', models.BooleanField(default=True)),
                ('default_min_age', models.PositiveSmallIntegerField(blank=True, help_text='Minimum entry age normally. NULL = all ages welcome.', null=True)),
                ('evening_min_age', models.PositiveSmallIntegerField(blank=True, help_text='Min age that applies after `evening_cutoff` (e.g. 21+ after 8pm).', null=True)),
                ('evening_cutoff', models.TimeField(blank=True, help_text='Local time after which evening_min_age applies.', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_food', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifa_match_number', models.PositiveIntegerField(blank=True, help_text='Canonical FIFA fixture number; the stable natural key.', null=True, unique=True)),
                ('stage', models.CharField(choices=[('group', 'Group stage'), ('r32', 'Round of 32'), ('r16', 'Round of 16'), ('qf', 'Quarterfinal'), ('sf', 'Semifinal'), ('third', 'Third place'), ('final', 'Final')], max_length=8)),
                ('group', models.CharField(blank=True, max_length=1)),
                ('kickoff', models.DateTimeField(help_text='Store timezone-aware (UTC).')),
                ('host_city', models.CharField(blank=True, max_length=80)),
                ('host_stadium', models.CharField(blank=True, max_length=120)),
                ('home_placeholder', models.CharField(blank=True, help_text='e.g. "Winner Group C"', max_length=60)),
                ('away_placeholder', models.CharField(blank=True, max_length=60)),
                ('bracket_slot', models.CharField(blank=True, help_text='Stable knockout slot id, e.g. "R32-3", so resolution can be re-applied.', max_length=20)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='events.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='events.team')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('all_matches', 'Shows every match'), ('by_team', 'Shows matches involving selected teams'), ('specific', 'Shows a specific set of matches')], max_length=16)),
                ('default_cost_type', models.CharField(choices=[('free_open', 'Free, open entry'), ('free_registration', 'Free, registration required'), ('free_lottery', 'Free, lottery (entry not guaranteed)'), ('free_minimum', 'Free entry, purchase/table minimum'), ('ticketed', 'Ticketed / paid')], default='free_open', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('matches', models.ManyToManyField(blank=True, related_name='screening_policies', to='events.match')),
                ('teams', models.ManyToManyField(blank=True, related_name='screening_policies', to='events.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(help_text='Often == match.kickoff, but may differ (doors).')),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cost_type', models.CharField(choices=[('free_open', 'Free, open entry'), ('free_registration', 'Free, registration required'), ('free_lottery', 'Free, lottery (entry not guaranteed)'), ('free_minimum', 'Free entry, purchase/table minimum'), ('ticketed', 'Ticketed / paid')], default='free_open', max_length=20)),
                ('registration_required', models.BooleanField(default=False)),
                ('entry_guaranteed', models.BooleanField(default=True, help_text='False for capped/lottery sessions.')),
                ('price_note', models.CharField(blank=True, help_text='e.g. "$10", "$80 incl. transit".', max_length=120)),
                ('age_override', models.PositiveSmallIntegerField(blank=True, help_text="Screening-specific min age; overrides the venue's rule when set.", null=True)),
                ('is_generated', models.BooleanField(default=False, help_text='True if materialized from a ScreeningPolicy.')),
                ('source', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='events.match')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='events.venue')),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'match', 'starts_at'), name='uniq_screening_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='VenueAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_type', models.CharField(choices=[('national_hub', 'National team supporters hub'), ('club_home', 'Club home bar')], max_length=16)),
                ('club', models.CharField(blank=True, help_text='Set for club_home, e.g. "Liverpool FC".', max_length=80)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(blank=True, help_text='Set for national_hub.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_hubs', to='events.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='events.venue')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('affiliation_type', 'national_hub'), ('team__isnull', False)), models.Q(('affiliation_type', 'club_home'), models.Q(('club', ''), _negated=True)), _connector='OR'), name='affiliation_target_matches_type')],
            },
        ),
    ]
