# Generated by Django 6.0.6 on 2026-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_attribution',
            field=models.CharField(blank=True, help_text='Required attribution text captured from Places photo metadata.', max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_source',
            field=models.CharField(blank=True, help_text='How the image is sourced, e.g. "google_places". Blank = fallback.', max_length=32),
        ),
        migrations.AddField(
            model_name='venue',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Place ID; resolved once via `resolvevenueplaces`.', max_length=255),
        ),
    ]
