# Generated by Django 6.0.6 on 2026-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venue_image_attribution_venue_image_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, help_text='Stable external image URL for the Wikimedia tier. Google photos stay proxy-resolved and do NOT use this field.', max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_attribution',
            field=models.CharField(blank=True, help_text='Required attribution text captured from the image source metadata.', max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_source',
            field=models.CharField(blank=True, help_text='How the image is sourced: "google_places", "wikimedia", or blank = fallback.', max_length=32),
        ),
    ]
