# Generated by Django 6.0.6 on 2026-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_image_url_alter_venue_image_attribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image_source',
            field=models.CharField(blank=True, help_text='How the image is sourced: "google_places" or "wikimedia" (confirmed, shown), "candidate" (a Google match awaiting review — falls back until confirmed), or blank = category fallback. Independent of `needs_review`, which is a data-quality flag from the import.', max_length=32),
        ),
    ]
