# Generated by Django 6.0.6 on 2026-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_image_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixtures_refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
